openapi: 3.0.0
info:
  title: Reading List API
  description: API for managing a reading list
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /books:
    post:
      description: ""
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  example: any
                author:
                  example: any
                status:
                  example: any
    get:
      description: ""
      responses:
        "200":
          description: OK
  /books/{uuid}:
    put:
      description: ""
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  example: any
    get:
      description: ""
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
    delete:
      description: ""
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /healthz:
    get:
      description: ""
      responses:
        "200":
          description: OK
